services:
  - type: web
    name: cardmap-backend
    runtime: java
    region: singapore
    plan: free
    branch: main
    buildCommand: ./gradlew clean build -x test
    startCommand: java -Dspring.profiles.active=prod -jar build/libs/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: prod
